repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: golangci-lint-mod
      - id: my-cmd
        name: goimports
        alias: goimports
        args: [ tools/ci/goimports.sh, github.com/bookstairs/bookstairs ]
